# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 18:58
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractParameters',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('genesis_block', models.BigIntegerField()),
                ('blocks_per_round', models.BigIntegerField()),
                ('challenge_cost', models.DecimalField(decimal_places=0, max_digits=80,
                                                       validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
        migrations.CreateModel(
            name='ContractState',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.BigIntegerField(unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('current_round', models.BigIntegerField()),
                ('current_subblock', models.BigIntegerField()),
                ('last_checkpoint_submission_round', models.BigIntegerField()),
                ('last_checkpoint', models.CharField(max_length=40)),
                ('is_checkpoint_submitted_for_current_round', models.BooleanField()),
                ('has_missed_checkpoint_submission', models.BooleanField()),
                ('live_challenge_count', models.BigIntegerField()),
                ('pending_withdrawals', models.DecimalField(decimal_places=0, max_digits=80,
                                                            validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('deposits', models.DecimalField(decimal_places=0, max_digits=80, validators=[
                 django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_balance', models.DecimalField(decimal_places=0, max_digits=80,
                                                      validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
    ]
