# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractstate',
            name='current_round',
        ),
        migrations.RemoveField(
            model_name='contractstate',
            name='current_subblock',
        ),
        migrations.AlterField(
            model_name='contractstate',
            name='last_checkpoint',
            field=models.CharField(max_length=64),
        ),
    ]
