# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-11 15:09
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_auto_20180329_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.BigIntegerField()),
                ('from_address', models.CharField(max_length=40)),
                ('to_address', models.CharField(max_length=40)),
                ('gas', models.BigIntegerField()),
                ('data', models.TextField()),
                ('value', models.DecimalField(decimal_places=0, max_digits=80, validators=[
                 django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nonce', models.BigIntegerField()),
                ('tag', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EthereumTransactionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.BigIntegerField()),
                ('gas_price', models.DecimalField(decimal_places=0, max_digits=80, validators=[
                 django.core.validators.MinValueValidator(Decimal('0'))])),
                ('signed_attempt', models.TextField()),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('mined', models.BigIntegerField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='contractor.EthereumTransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
