# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-25 11:35
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_auto_20180824_1558'),
        ('contractor', '0003_ethereumtransaction_ethereumtransactionattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLedgerState',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_withdrawals', models.DecimalField(decimal_places=0, max_digits=80,
                                                            validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('deposits', models.DecimalField(decimal_places=0, max_digits=80, validators=[
                 django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_balance', models.DecimalField(decimal_places=0, max_digits=80,
                                                      validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contractstate',
            name='deposits',
        ),
        migrations.RemoveField(
            model_name='contractstate',
            name='pending_withdrawals',
        ),
        migrations.RemoveField(
            model_name='contractstate',
            name='total_balance',
        ),
        migrations.AddField(
            model_name='contractledgerstate',
            name='contract_state',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='contractor.ContractState'),
        ),
        migrations.AddField(
            model_name='contractledgerstate',
            name='token',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='ledger.Token'),
        ),
    ]
