# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0005_contractledgerstate_confirmed_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractparameters',
            name='rounds_kept',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
