# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0006_contractparameters_rounds_kept'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractstate',
            name='basis',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
