# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0007_contractstate_basis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractparameters',
            old_name='blocks_per_round',
            new_name='blocks_per_eon',
        ),
        migrations.RenameField(
            model_name='contractparameters',
            old_name='rounds_kept',
            new_name='eons_kept',
        ),
        migrations.RenameField(
            model_name='contractstate',
            old_name='is_checkpoint_submitted_for_current_round',
            new_name='is_checkpoint_submitted_for_current_eon',
        ),
        migrations.RenameField(
            model_name='contractstate',
            old_name='last_checkpoint_submission_round',
            new_name='last_checkpoint_submission_eon',
        ),
    ]
