# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0008_auto_20190320_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumtransaction',
            name='nonce',
            field=models.BigIntegerField(unique=True),
        ),
    ]
