# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0069_multi_eon_matching_tokens_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOSConfig',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy_digest', models.CharField(max_length=64)),
                ('terms_of_service_digest', models.CharField(max_length=64)),
                ('time', models.DateTimeField(db_index=True,
                                              default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TOSSignature',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('tos_config', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.PROTECT, to='tos.TOSConfig')),
                ('tos_signature', models.ForeignKey(blank=True, null=True,
                                                    on_delete=django.db.models.deletion.PROTECT, to='ledger.Signature')),
                ('address', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tosconfig',
            unique_together=set(
                [('privacy_policy_digest', 'terms_of_service_digest')]),
        ),
        migrations.AlterUniqueTogether(
            name='tossignature',
            unique_together=set([('address', 'tos_config')]),
        ),
    ]
