# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20171229_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
