# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_wallet_registration_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='registration_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='wallet_registration_signature', to='ledger.Signature'),
        ),
    ]
