# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_auto_20171230_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointsubmission',
            name='blockchaintransaction_ptr',
        ),
        migrations.RemoveField(
            model_name='checkpointsubmission',
            name='checkpoint',
        ),
        migrations.DeleteModel(
            name='CheckpointSubmission',
        ),
    ]
