# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_auto_20180106_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockchainTransaction',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='highest_spendings',
        ),
        migrations.AddField(
            model_name='deposit',
            name='txid',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='txid',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='txid',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='block',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='block',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='block',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
