# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 13:07
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20180106_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=80, validators=[
                 django.core.validators.MinValueValidator(Decimal('0'))])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('round', models.BigIntegerField()),
                ('txid', models.CharField(max_length=256)),
                ('block', models.BigIntegerField(blank=True, null=True)),
                ('response_txid', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('balance', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.PROTECT, to='ledger.Balance')),
                ('wallet', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='ledger.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
