# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 10:41
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20180108_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceMarker',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=80, validators=[
                 django.core.validators.MinValueValidator(Decimal('0'))])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('round', models.BigIntegerField()),
                ('signature', models.ForeignKey(blank=True, null=True,
                                                on_delete=django.db.models.deletion.PROTECT, to='ledger.Signature')),
                ('wallet', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='ledger.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
