# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_balancemarker'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='slashed',
            field=models.BooleanField(default=False),
        ),
    ]
