# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_delete_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='recipient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT,
                                    related_name='challenge_recipient_wallet', to='ledger.Wallet'),
            preserve_default=False,
        ),
    ]
