# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_blacklistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregate',
            name='tx_set_proof_hashes',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
