# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_aggregate_tx_set_proof_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregate',
            name='tx_set_index',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
