# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_aggregate_tx_set_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='trail_identifier',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
