# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-25 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_wallet_trail_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='final_receipt_hashes',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='final_receipt_index',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
