# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-11 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_auto_20180625_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='response_txid',
        ),
        migrations.AddField(
            model_name='challenge',
            name='rebuted',
            field=models.BooleanField(default=False),
        ),
    ]
