# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 15:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_auto_20180711_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, unique=True)),
                ('index', models.IntegerField(unique=True, validators=[
                 django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='wallet',
            name='token',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, to='ledger.Token'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set([('token', 'address')]),
        ),
    ]
