# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_auto_20180824_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='trail_identifier',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(
                [('token', 'address'), ('token', 'trail_identifier')]),
        ),
    ]
