# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_auto_20180824_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='index',
            new_name='trail',
        ),
    ]
