# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0024_auto_20180824_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.BigIntegerField()),
                ('basis', models.CharField(max_length=64)),
                ('merkle_root', models.CharField(max_length=64)),
                ('block', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='block',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='round',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='membership_hashes',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='token',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, to='ledger.Token'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rootcommitment',
            unique_together=set([('round', 'basis')]),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='root_commitment',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.RootCommitment'),
        ),
    ]
