# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-25 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_auto_20180824_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='short_name',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
