# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-25 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0027_auto_20180825_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='block',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
