# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 14:26
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_auto_20180825_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='balance',
        ),
        migrations.AddField(
            model_name='transfer',
            name='amount_swapped',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, validators=[
                                      django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
