# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-15 13:00
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0029_auto_20180914_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('left_deducted_right_granted_amount', models.DecimalField(decimal_places=0,
                                                                           max_digits=80, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('right_deducted_left_granted_amount', models.DecimalField(decimal_places=0,
                                                                           max_digits=80, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('left_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='matching_left_order', to='ledger.Transfer')),
                ('right_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='matching_right_order', to='ledger.Transfer')),
            ],
        ),
    ]
