# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-15 13:04
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0030_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='extra_left_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80, validators=[
                                      django.core.validators.MinValueValidator(Decimal('0'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matching',
            name='extra_right_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=80, validators=[
                                      django.core.validators.MinValueValidator(Decimal('0'))]),
            preserve_default=False,
        ),
    ]
