# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0031_auto_20180915_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='finalization_aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_finalization_aggregate', to='ledger.Aggregate'),
        ),
    ]
