# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0032_transfer_finalization_aggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
