# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-22 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0035_pgsql_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='sender_balance_marker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='transfer_sender_balance_marker', to='ledger.BalanceMarker'),
            preserve_default=False,
        ),
    ]
