# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0037_auto_20180922_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='cancelled',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='complete',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='processed',
            field=models.NullBooleanField(),
        ),
    ]
