# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0038_auto_20180926_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
