# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0039_auto_20180926_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='appended',
            field=models.BooleanField(default=False),
        ),
    ]
