# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0040_transfer_appended'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='voided',
            field=models.BooleanField(default=False),
        ),
    ]
