# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0041_transfer_voided'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='finalization_aggregate',
            new_name='recipient_finalization_aggregate',
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_cancellation_aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_cancellation_aggregate', to='ledger.Aggregate'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_fulfillment_aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_fulfillment_aggregate', to='ledger.Aggregate'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_cancellation_aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='wallet_cancellation_aggregate', to='ledger.Aggregate'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='swap_freezing_signature',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='swap_freezing_signature', to='ledger.Signature'),
            preserve_default=False,
        ),
    ]
