# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0042_auto_20180927_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='swap_freezing_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='swap_freezing_signature', to='ledger.Signature'),
        ),
    ]
