# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-30 10:27
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0043_auto_20180927_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount_swapped',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, validators=[
                                      django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
