# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0044_auto_20180930_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPair',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('conduit', models.CharField(blank=True, max_length=40, unique=True)),
                ('token_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='from_pairs', to='ledger.Token')),
                ('token_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='to_pairs', to='ledger.Token')),
            ],
        ),
    ]
