# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-05 09:13
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0045_tokenpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='passive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, validators=[
                                      django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
