# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-08 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0046_auto_20190205_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='sender_finalization_aggregate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sender_finalization_aggregate', to='ledger.Aggregate'),
        ),
    ]
