# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0049_drop_pgsql_constraints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance',
            new_name='ExclusiveBalanceAllotment',
        ),
    ]
