# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0050_auto_20190320_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregate',
            old_name='round',
            new_name='eon_number',
        ),
        migrations.RenameField(
            model_name='balancemarker',
            old_name='round',
            new_name='eon_number',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='round',
            new_name='eon_number',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='round',
            new_name='eon_number',
        ),
        migrations.RenameField(
            model_name='exclusivebalanceallotment',
            old_name='round',
            new_name='eon_number',
        ),
        migrations.RenameField(
            model_name='rootcommitment',
            old_name='round',
            new_name='eon_number',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='round',
            new_name='eon_number',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='registration_round',
            new_name='registration_eon_number',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='round',
            new_name='eon_number',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='round',
            new_name='eon_number',
        ),
        migrations.AlterUniqueTogether(
            name='exclusivebalanceallotment',
            unique_together=set([('wallet', 'eon_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='rootcommitment',
            unique_together=set([('eon_number', 'basis')]),
        ),
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together=set(
                [('eon_number', 'wallet', 'nonce'), ('eon_number', 'recipient', 'nonce')]),
        ),
    ]
