# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 17:16
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0051_auto_20190320_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aggregate',
            new_name='activestate',
        ),
        migrations.AlterField(
            model_name='activestate',
            name='hub_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='active_state_hub_signature', to='ledger.Signature'),
        ),
        migrations.AlterField(
            model_name='activestate',
            name='wallet_signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='active_state_wallet_signature', to='ledger.Signature'),
        ),


        migrations.RenameField(
            model_name='exclusivebalanceallotment',
            old_name='merkle_proof_aggregate',
            new_name='active_state',
        ),
        migrations.AlterField(
            model_name='exclusivebalanceallotment',
            name='active_state',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.ActiveState'),
        ),


        migrations.RenameField(
            model_name='transfer',
            old_name='recipient_aggregate',
            new_name='recipient_active_state',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_active_state', to='ledger.ActiveState'),
        ),

        migrations.RenameField(
            model_name='transfer',
            old_name='recipient_cancellation_aggregate',
            new_name='recipient_cancellation_active_state',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_cancellation_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_cancellation_active_state', to='ledger.ActiveState'),
        ),

        migrations.RenameField(
            model_name='transfer',
            old_name='recipient_finalization_aggregate',
            new_name='recipient_finalization_active_state',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_finalization_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_finalization_active_state', to='ledger.ActiveState'),
        ),

        migrations.RenameField(
            model_name='transfer',
            old_name='recipient_fulfillment_aggregate',
            new_name='recipient_fulfillment_active_state',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_fulfillment_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_fulfillment_active_state', to='ledger.ActiveState'),
        ),

        migrations.RenameField(
            model_name='transfer',
            old_name='sender_aggregate',
            new_name='sender_active_state',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_active_state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sender_active_state', to='ledger.ActiveState'),
            preserve_default=False,
        ),

        migrations.RenameField(
            model_name='transfer',
            old_name='sender_cancellation_aggregate',
            new_name='sender_cancellation_active_state',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_cancellation_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sender_cancellation_active_state', to='ledger.ActiveState'),
        ),

        migrations.RenameField(
            model_name='transfer',
            old_name='sender_finalization_aggregate',
            new_name='sender_finalization_active_state',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_finalization_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sender_finalization_active_state', to='ledger.ActiveState'),
        ),


        migrations.AlterField(
            model_name='transfer',
            name='swap_freezing_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='swap_freezing_signature', to='ledger.Signature'),
        ),
    ]
