# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0052_auto_20190320_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activestate',
            old_name='hub_signature',
            new_name='operator_signature',
        ),
        migrations.AlterField(
            model_name='activestate',
            name='operator_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='active_state_operator_signature', to='ledger.Signature'),
        ),

        migrations.RenameField(
            model_name='wallet',
            old_name='registration_hub_authorization',
            new_name='registration_operator_authorization',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='registration_operator_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='operator_registration_signature', to='ledger.Signature'),
        ),
    ]
