# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0053_auto_20190320_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalanceMarker',
            new_name='MinimumAvailableBalanceMarker',
        ),
    ]
