# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-07 15:45
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0055_pgsql_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestate',
            name='eon_number',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='eon_number',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='eon_number',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='exclusivebalanceallotment',
            name='active_state',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.ActiveState'),
        ),
        migrations.AlterField(
            model_name='exclusivebalanceallotment',
            name='eon_number',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='minimumavailablebalancemarker',
            name='eon_number',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rootcommitment',
            name='eon_number',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='address',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='trail',
            field=models.IntegerField(db_index=True, unique=True, validators=[
                                      django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='appended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='eon_number',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='nonce',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=80, null=True, validators=[
                                      django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='passive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='position',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=80, null=True, validators=[
                                      django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_active_state', to='ledger.ActiveState'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_cancellation_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_cancellation_active_state', to='ledger.ActiveState'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_finalization_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_finalization_active_state', to='ledger.ActiveState'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_fulfillment_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='recipient_fulfillment_active_state', to='ledger.ActiveState'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_active_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sender_active_state', to='ledger.ActiveState'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_cancellation_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sender_cancellation_active_state', to='ledger.ActiveState'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_finalization_active_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sender_finalization_active_state', to='ledger.ActiveState'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='voided',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='registration_eon_number',
            field=models.BigIntegerField(db_index=True, validators=[
                                         django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='trail_identifier',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='eon_number',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='eon_number',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
