# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 13:16
from __future__ import unicode_literals

from django.db import migrations, models, transaction
import django.db.models.deletion


def populate_index_field(apps, schema_editor):
    Transfer = apps.get_model('ledger', 'Transfer')

    # cannot use effecient bulk updates, because of django ORM limitations
    with transaction.atomic():
        recipient_sets = Transfer.objects.filter(
            recipient_active_state__isnull=False,
            recipient_merkle_index__isnull=True
        )
        sender_sets = Transfer.objects.filter(
            sender_active_state__isnull=False,
            sender_merkle_index__isnull=True
        )

        for tx in recipient_sets:
            tx.recipient_merkle_index = tx.recipient_active_state.tx_set_index
            tx.save()

        for tx in sender_sets:
            tx.sender_merkle_index = tx.sender_active_state.tx_set_index
            tx.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0056_auto_20190507_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='sender_merkle_hash_cache',
            field=models.CharField(blank=True, max_length=2080, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_merkle_height_cache',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_merkle_hash_cache',
            field=models.CharField(blank=True, max_length=2080, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_merkle_height_cache',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_merkle_index',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_merkle_index',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='transfer',
        #     name='sender_merkle_root_cache',
        #     field=models.CharField(max_length=65, blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='transfer',
        #     name='recipient_merkle_root_cache',
        #     field=models.CharField(max_length=65, blank=True, null=True),
        # ),
        migrations.RunPython(populate_index_field),
    ]
