# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0058_pgsql_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='wallet',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.Wallet'),
        ),
    ]
