# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 18:25
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0059_signature_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='swap',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
