# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 18:25
from __future__ import unicode_literals
from django.db import migrations, models, transaction


def populate_swap_field(apps, schema_editor):
    Transfer = apps.get_model('ledger', 'Transfer')

    with transaction.atomic():
        for tx in Transfer.objects.all():
            tx.swap = tx.amount_swapped is not None
            tx.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0060_auto_20190704_1825'),
    ]

    operations = [
        migrations.RunPython(populate_swap_field),
    ]
