# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 07:12
from __future__ import unicode_literals

from django.db import migrations, models
from decimal import Decimal
import django.core.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0062_pgsql_constraints'),
    ]

    operations = [
        # update transfer
        migrations.AddField(
            model_name='transfer',
            name='recipient_starting_balance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, validators=[
                django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_starting_balance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=80, null=True, validators=[
                                      django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='transfer',
            name='tx_id',
            field=models.UUIDField(
                blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),

        # update matching
        migrations.AddField(
            model_name='matching',
            name='eon_number',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_order_tx_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_order_tx_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),

        # update time field
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='time',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='time',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='time',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='time',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
