# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 07:12
from __future__ import unicode_literals

from django.db import migrations, transaction
import uuid


def populate_tx_id_field(apps, schema_editor):
    Transfer = apps.get_model('ledger', 'Transfer')

    with transaction.atomic():
        for t in Transfer.objects.all():
            t.tx_id = uuid.uuid4()
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0063_multi_eon_swaps'),
    ]

    operations = [
        migrations.RunPython(populate_tx_id_field),
    ]
