# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0064_multi_eon_swaps_populate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together=set([('eon_number', 'tx_id'), ('eon_number',
                                                           'wallet', 'nonce'), ('eon_number', 'recipient', 'nonce')]),
        ),
    ]
