# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 07:12
from __future__ import unicode_literals

from django.db import migrations, transaction


def populate_matching_eon_number_field(apps, schema_editor):
    Matching = apps.get_model('ledger', 'Matching')

    with transaction.atomic():
        for m in Matching.objects.all():
            m.eon_number = m.left_order.eon_number
            m.left_order_tx_id = m.left_order.tx_id
            m.right_order_tx_id = m.right_order.tx_id
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0065_multi_eon_swaps_index'),
    ]

    operations = [
        migrations.RunPython(populate_matching_eon_number_field),
    ]
