# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0066_multi_eon_matching_populate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='left_order',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='right_order',
        ),
    ]
