# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 07:12
from __future__ import unicode_literals

from django.db import migrations, transaction


def populate_matching_token_field(apps, schema_editor):
    Matching = apps.get_model('ledger', 'Matching')
    Transfer = apps.get_model('ledger', 'Transfer')

    with transaction.atomic():
        for m in Matching.objects.all():
            t_left = Transfer.objects.get(
                tx_id=m.left_order_tx_id, eon_number=m.eon_number)
            # t_right = Transfer.objects.get(
            #     tx_id=m.left_order_tx_id, eon_number=m.eon_number)
            m.left_token = t_left.wallet.token
            m.right_token = t_left.recipient.token
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0068_multi_eon_matching_tokens'),
    ]

    operations = [
        migrations.RunPython(populate_matching_token_field),
    ]
