# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-14 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0058_pgsql_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ledger.transfer',),
        ),
    ]
