name: Run tests

on: pull_request
 
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6,]

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: liquidity
          POSTGRES_PASSWORD: liquidity
          POSTGRES_BD: liquidity
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      cache:
        image: redis:alpine
        ports: ['6379:6379']

    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}        
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-serv.txt
        pip install -r requirements-dev.txt
        curl --silent --location https://deb.nodesource.com/setup_10.x | sudo bash -
        sudo apt-get install --yes nodejs build-essential git
        sudo npm install -g --unsafe-perm ganache-cli

    - name: Checkout contract
      uses: actions/checkout@v2
      with: 
        repository: liquidity-network/just-deploy
        token: ${{secrets.PAT}}
        path: just-deploy

    - name: Run Unittests
      run: |
        python operator_api/manage.py test --parallel --pattern unittest*.py

    - name: Run Tests
      env:
        RUN_STARTUP_TASKS: true
      run: |
        cd operator_api
        pytest -v -x
